#!/usr/bin/env python3
"""Generate docs/catalog.md from all rule files in rules/.

Output is a sorted markdown catalog with one section per category and a table
per file showing alert name, severity, priority, expression (truncated),
and runbook link.

Usage:
    python3 scripts/generate_catalog.py > docs/catalog.md
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("ERROR: pyyaml not installed. Install via: pip3 install pyyaml\n")
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = REPO_ROOT / "rules"

EXPR_TRUNC = 80


def truncate(s: str, n: int) -> str:
    s = " ".join(s.split())  # collapse whitespace
    if len(s) <= n:
        return s
    return s[: n - 1] + "\u2026"


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def main() -> int:
    if not RULES_DIR.is_dir():
        sys.stderr.write(f"ERROR: {RULES_DIR} not found\n")
        return 2

    by_category: dict[str, list[Path]] = {}
    for f in sorted(RULES_DIR.rglob("*.yaml")):
        cat = f.parent.name
        by_category.setdefault(cat, []).append(f)

    print("# Alert catalog")
    print()
    print("> Auto-generated by `scripts/generate_catalog.py`. Do not edit by hand.")
    print()

    total_alerts = 0
    file_count = 0

    for cat in sorted(by_category):
        print(f"## {cat}")
        print()
        for f in by_category[cat]:
            file_count += 1
            try:
                with f.open() as fh:
                    doc = yaml.safe_load(fh)
            except Exception as exc:
                print(f"<!-- {f.relative_to(REPO_ROOT)}: parse error: {exc} -->")
                print()
                continue

            stem = f.stem
            print(f"### `{f.relative_to(REPO_ROOT)}`")
            print()
            print("| Alert | Severity | Priority | For | Signal | Expression | Runbook |")
            print("|---|---|---|---|---|---|---|")

            if not doc or "groups" not in doc:
                print()
                continue

            for group in doc["groups"]:
                for rule in group.get("rules", []):
                    if "alert" not in rule:
                        continue
                    total_alerts += 1
                    name = rule["alert"]
                    labels = rule.get("labels") or {}
                    sev = labels.get("severity", "")
                    prio = labels.get("priority", "")
                    sig = labels.get("signal", "")
                    runbook = labels.get("runbook", "")
                    for_ = rule.get("for", "")
                    expr = rule.get("expr", "")
                    if isinstance(expr, str):
                        expr_disp = "`" + truncate(expr, EXPR_TRUNC) + "`"
                    else:
                        expr_disp = ""
                    runbook_disp = f"[{Path(runbook).name}]({runbook})" if runbook else ""
                    print(
                        f"| `{name}` | {sev} | {prio} | {for_} | {sig} | "
                        f"{md_escape(expr_disp)} | {runbook_disp} |"
                    )
            print()

    print("---")
    print()
    print(f"_{total_alerts} alerts across {file_count} files in {len(by_category)} categories._")
    return 0


if __name__ == "__main__":
    sys.exit(main())
